pub mod diff;
pub mod error;
pub mod gc;
pub mod hash;
pub mod hooks;
pub mod ignore;
pub mod index;
pub mod merge;
pub mod module;
pub mod object;
pub mod protocol;
pub mod refs;
pub mod remote;
pub mod repository;
pub mod storage;

pub use diff::{Change, DiffEngine, FileDiff, Hunk};
pub use error::{Error, Result};
pub use hash::{Hash, Oid};
pub use hooks::{HookManager, HookResult, HookType};
pub use merge::{ConflictedFile, MergeManager, MergeResult, MergeStrategy};
pub use module::{ModuleManager, ModuleManifest, ModuleMetadata, ModuleType};
pub use object::{Blob, Commit, Object, ObjectType, Tree, TreeEntry};
pub use protocol::{ObjectData, ObjectType as ProtocolObjectType, RefUpdate, Request, Response};
pub use remote::{RemoteClient, RemoteConfig, RemoteManager};
pub use repository::Repository;
